### ISSUE TITLE
Disable Rails/Blank

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/oss-guides#44]

**Comment by skalee** [comment]
My bad. Earlier I forgot to do one thing. Should be properly disabled now.

**Comment by opoudjis** [comment]
As I just pinged you, I am still getting Rails reports in my rubocop; do I need to do anything to reload the latest rubocop config?

**Comment by skalee** [comment]
I really need a concrete example. Please give me a link to repository in which this problem occurs (if in all of them, then just give me a link to any repository in which you have experienced that).

Also, are these incorrect reports from Hound CI or from Rubocop that you execute locally?

**Comment by opoudjis** [comment]
Rubocop I run locally

**Comment by skalee** [comment]
I bet it's due to incorrect `.rubocop.yml`. This is the example of correct file:

```yml
inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

# local repo-specific modifications
# ...
```

(https://github.com/riboseinc/oss-guides/blob/0f6a733a403a63a3bb103e0b7c7f6b24207d1221/for_new_projects/ruby/.rubocop.yml)

----

I guess I need to think out something to make this setup easier to use and less error prone, but such improvement may require another changes in configuration in projects. Maybe Cimas will help to perform such mass update?

**Comment by opoudjis** [comment]
Yes it will. @CAMOBAP?

But I do have the correct file.

isodoc/.rubocop.yml:

````
# This project follows the Ribose OSS style guide.
# https://github.com/riboseinc/oss-guides
# All project-specific additions and overrides should be specified in this file.
inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

# local repo-specific modifications

AllCops:
  DisplayCopNames: false
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.4
Rails:
  Enabled: true
```` 

And isodoc is still complaining about Rails errors like Rails/Blank.
